version: '2'
services:
  plexmediaserver:
    container_name: PlexMediaServer
    restart: unless-stopped
    image: linuxserver/plex:latest
    environment:
    - TZ=America/Chicago
    - VERSION=latest
    - PLEX_CLAIM=""
    - net=host
    ports:
    - "32400:32400" #(for access to the Plex Media Server) [required]
    # - "32400:32400/udp"
    # - "32410:32410/udp" #(for current GDM network discovery)
    # - "32412:32412/udp"
    # - "32413:32413/udp"
    # - "32414:32414/udp"
    # - "32469:32469" #(for access to the Plex DLNA Server)
    # - "32469:32469/udp"
    # - "5353:5353" # (for older Bonjour/Avahi network discovery)
    #- "1900:1900/udp" #(for access to the Plex DLNA Server)

    volumes:
    - /docker/plex/PlexMediaServer:/config
    - /docker/plex/PlexMediaServer/Movies:/data/movies
    - /docker/plex/PlexMediaServer/TVShows:/data/tvshows
    - /docker/plex/PlexMediaServer/Music:/data/music
    - /docker/plex/PlexMediaServer/HomeMedia:/data/homemedia
    - /docker/plex/PlexMediaServer/Photos:/data/photos
    networks:
      - plexnet
  plextransmission:
    container_name: PlexTransmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/plex/PlexTransmission:/data
      - /docker/plex/PlexTransmission/shared:/shared
      - /docker/plex/PlexTransmission/Downloads:/data/watch
      - /docker/plex/PlexTransmission/completed:/data/completed
      - /docker/plex/PlexTransmission/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=ahumphries003@gmail.com
      - OPENVPN_PASSWORD=Humps003
      - OPENVPN_CONFIG="mke-c02.ipvanish.com"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=Humps003
      - TRANSMISSION_RPC_USERNAME=administrator
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    networks:
      - plexnet
  plexradarr:
    image: "linuxserver/radarr"
    container_name: "PlexRadarr"
    volumes:
      #- /docker/plex/PlexRadarr:/config
      #- /docker/plex/PlexRadarr/Downloads/completed:/downloads
      #- /docker/plex/PlexRadarr/Media/Movies:/movies
      #- /etc/localtime:/etc/localtime:ro
      #- /docker/plex/PlexRadarr/docker/shared:/shared
      - /docker/plex/PlexRadarr/config:/config
      #- /docker/plex/PlexSonarr/TVShows:/tv
      - /docker/plex/PlexMediaServer/Movies:/movies
      - /docker/plex/PlexTransmission/completed:/data/completed
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Chicago
    networks:
      - plexnet
  plexsonarr:
    image: linuxserver/sonarr
    container_name: PlexSonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/plex/PlexSonarr/config:/config
      #- /docker/plex/PlexSonarr/TVShows:/tv
      - /docker/plex/PlexMediaServer/TVShows:/tv
      - /docker/plex/PlexTransmission/completed:/data/completed
  plexjackett:
    image: linuxserver/jackett
    container_name: PlexJackett
    restart: always
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1001
      - TZ=America/Chicago
    volumes:
      - /docker/plex/PlexJackett/config:/config
      - /docker/plex/PlexJackett/downloads:/downloads
    ports:
      - "9117:9117"
    networks:
      - plexnet
networks:
  plexnet:
    driver: bridge
